---
- name: create a virtual machine on given ESXi hostname
  hosts: localhost
  tasks:
    - name: create a new machine
      vmware_guest:
        hostname: CDG-VCENTER.hsilab.com
        username: administrator@vsphere.local
        password: T!g3r@Ind!A
        validate_certs: no
        datacenter: HSILAB
        folder: Ansible
        name: Pradee_test_ansible-17082023
        guest_id: rhel8_64Guest
        datastore: CDG_Datastore1
        networks:
        - name: VM Network
          ip: 192.168.101.130
          netmask: 255.255.254.0
          gateway: 192.168.100.1
          device_type: vmxnet3
          start_connected: yes
        wait_for_ip_address: true
        cdrom:
           type: iso
           iso_path: "[CDG_Datastore3]   rhel-8.8-x86_64-dvd.iso"
        disk:
          - size_gb: 50
            type: thin
        hardware:
          memory_mb: 1600
          num_cpus: 8
        customization:
            hostname: "Sumittest"
            time_zone: "Asia/Kolkata"
            password: "Hitachi@123"
            fullname: "sumit bhagat"
            language: "en_IN"
            keyboard: "us"
            network: "VM Network"
