--- #MY PLAYBOOK
- hosts: Vcenter
  vars:
   ansible_connection: vmware_tools 
   ansible_vmware_validate_certs: no
 
  tasks:
    - name: Get the list of the monitored items
      vmware.vmware_rest.appliance_health_databasestorage_info:
      register: result

