---
- name: Gather facts about the cluster 
  hosts: localhost
  tasks:
    - name: Gather cluster facts from given datacenter
      vmware_cluster_info:
        hostname: CDG-VCENTER.hsilab.com
        username: administrator@vsphere.local
        password: T!g3r@Ind!A
        datacenter: HSILAB
        validate_certs: no

